# Exercises 13

In [9]:

# 1. Filter only negative and zero in the list using list comprehension
numbers = [-4, -3, -2, -1, 0, 2, 4, 6]
filtered_numbers = [num for num in numbers if num <= 0]
print(filtered_numbers, '\n')

# 2. Flatten the list of lists of lists to a one-dimensional list
list_of_lists = [[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]]
flattened_list = [num for sublist in list_of_lists for subsublist in sublist for num in subsublist]
print(flattened_list,'\n')

# 3. Create a list of tuples using list comprehension

tuple_list = [(i, 1, i, i**2, i**3, i**4, i**5) for i in range(11)]

# Printing the list of tuples
for tpl in tuple_list:
    print(tpl)

# 4. Flatten the list of countries to a new list
countries = [[('Finland', 'Helsinki')], [('Sweden', 'Stockholm')], [('Norway', 'Oslo')]]
flattened_countries = [[country.upper(), country[:3].upper(), city.upper()] for sublist in countries for (country, city) in sublist]
print(flattened_countries)

# 5. Change the list of countries to a list of dictionaries
countries_dict = [{'country': country.upper(), 'city': city.upper()} for sublist in countries for (country, city) in sublist]
print(countries_dict)

# 6. Change the list of lists to a list of concatenated strings
names = [[('Asabeneh', 'Yetayeh')], [('David', 'Smith')], [('Donald', 'Trump')], [('Bill', 'Gates')]]
concatenated_names = [' '.join(name) for sublist in names for name in sublist]
print(concatenated_names)

# 7. Lambda function to solve for slope or y-intercept of a linear function
linear_function_solver = lambda x1, y1, x2, y2, solve_for: (y2 - y1) / (x2 - x1) if solve_for == 'slope' else y1 - ((y2 - y1) / (x2 - x1)) * x1

[-4, -3, -2, -1, 0]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

(0, 1, 0, 0, 0, 0, 0)
(1, 1, 1, 1, 1, 1, 1)
(2, 1, 2, 4, 8, 16, 32)
(3, 1, 3, 9, 27, 81, 243)
(4, 1, 4, 16, 64, 256, 1024)
(5, 1, 5, 25, 125, 625, 3125)
(6, 1, 6, 36, 216, 1296, 7776)
(7, 1, 7, 49, 343, 2401, 16807)
(8, 1, 8, 64, 512, 4096, 32768)
(9, 1, 9, 81, 729, 6561, 59049)
(10, 1, 10, 100, 1000, 10000, 100000)
[['FINLAND', 'FIN', 'HELSINKI'], ['SWEDEN', 'SWE', 'STOCKHOLM'], ['NORWAY', 'NOR', 'OSLO']]
[{'country': 'FINLAND', 'city': 'HELSINKI'}, {'country': 'SWEDEN', 'city': 'STOCKHOLM'}, {'country': 'NORWAY', 'city': 'OSLO'}]
['Asabeneh Yetayeh', 'David Smith', 'Donald Trump', 'Bill Gates']